### PR TITLE
Button - disable Hover prop to make mobile friendly 

### PR DESCRIPTION
**Pull request by lukeschunk**
potential way to disable hover to make mobile friendly

### CODE REVIEW

**Comment by iheartrachie** [comment]
:shipit:

**Comment by lukeschunk** [comment]
decided that @vintagepenguin 's way of doing this was better (https://github.com/mxenabled/mx-react-components/pull/398/files)

**Comment by iheartrachie** [comment]
Looks good! :shipit:

**Comment by iheartrachie** [comment]
Looks good! :shipit:

**Comment by vintagepenguin** [comment]
:shipit:

**Pull request merged**
