### PR TITLE
TimeBasedLineChart: Rename hoverCallBack to onDataPointHover

### LINKED ISSUE #83: Rename `hoverCallBack` to `onDataPointHover` in TimeBasedLineChart

### PR DESCRIPTION
**Pull request by bsbeeks**
Fixes #83 

@cerinman @jmophoto

### CODE REVIEW

**Comment by cerinman** [comment]
Travis is failing.  I think it is because the renamed callback is out of alphabetical order in the list now.

**Comment by bsbeeks** [comment]
@cerinman this is passing now

**Comment by bsbeeks** [comment]
boo....conflicts.

**Comment by cerinman** [comment]
hahaha

**Comment by cerinman** [comment]
:shipit:

**Pull request merged**
