### PR TITLE
Add theme to Button

### PR DESCRIPTION
**Pull request by jtanner**
_Targets: `joe/theme-master` branch for #588_

This introduces a pattern for adding a `theme` prop to a component while keeping the `primaryColor` prop in place but deprecated.

Here's an example of the demo with themed buttons:

screen shot 2017-06-07 at 10 09 06 am

### CODE REVIEW

**Comment by iheartrachie** [comment]
I don't know how this relates to other places we are using theme but I find customizing `GRAY_500` or any other color-specific name a little confusing. In the context of buttons, I think it makes more sense to have a `disabled` color variable in the theme. But again, not sure how that plays with other places we're using theme.

**Comment by jtanner** [comment]
@iheartrachie that's a good point. Having a `disabled` color makes sense especially because the theme color names are meant to be more semantic and descriptive of how they're used. Let's discuss it more and if we decide to go that route I'll put up another PR 👌

**Comment by iheartrachie** [comment]
:shipit:

**Comment by jtanner** [comment]
@cerinman @iheartrachie I added some docs for theming. What do you think of the wording? Is is clear enough?

Here's what it looks like:

screen shot 2017-06-08 at 11 22 02 am

**Comment by jmophoto** [comment]
:shipit:

**Pull request merged**
