### PR TITLE
Icon: Up/Down fat arrows

### PR DESCRIPTION
**Pull request by tumentumurchudur**
- Added up/down fat arrows

screen shot 2016-01-26 at 11 27 55 am

### CODE REVIEW

**Comment by jmophoto** [comment]
Did you add these into the demo?

**Comment by bsbeeks** [comment]
they also shouldn't have colors

**Comment by tumentumurchudur** [comment]
Yes, I just added these colors in the demo.

**Comment by bsbeeks** [comment]
Add them to the demo dropdown, then :shipit:

**Pull request merged**
