### PR TITLE
DatePicker Component

### LINKED ISSUE #280: Improvements on Date Picker
Here are some things I noticed when trying to use the `DatePicker` component. I'd like feedback before I start making changes though. There may be other things that aren't working smoothly, these are just want I happened upon so far.

1. `useInputForSelectedDate` allows a user to input a value but on blur the value isn't saved or returns 'invalid date'
2. `defaultDate` overrides `placeholderText` when set. 
3. `defaultDate` should default to today. Thoughts?

### PR DESCRIPTION
**Pull request by iheartrachie**
This updates the DatePicker component to match the specs in the [style guide](https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/inputs/form-elements). This is only for single date selecting. Date range picker will be a separate component. This deprecates a number of options of the old component, predominantly the `useInputForSelectedDate` prop. Closes #280.

## Before
old

## After
new

## Example
``` js
_handleDateSelect (selectedDatePickerDate) {
  this.setState({
    selectedDatePickerDate
  });
},

<DatePicker
  closeOnDateSelect={true}
  onDateSelect={this._handleDateSelect}
  showDayBorders={false}
/>
```

## Props
`closeOnDateSelect` _boolean_ **optional**
Default: false
If set to `true`, the calendar will be close after the user selects a date.

`defaultDate _number_ **optional**
This sets the default selected date on component mount.

`format` _string_ **optional**
Default: 'MMM D, YYY'
This is used to determine the format of the selected date. It should follow the Moment.js conventions.

`locale` _string_ **optional**
Default: 'en'
This is used to format the dates, day names, month names, etc based on the locale.

`minimumDate` _number_ **optional**
If set, the user will not be able to select a date prior to this date.

`onDateSelect` _function_ **optional**
A function to be called when the user has selected a date. The selected date timestamp will be passed to this function.

`placeholderText` _string_ **optional**
Default: 'Select A Date'
A string used as placeholder text for the selected date input when it is empty.

`primaryColor` _string_ **optional**
Default: PRIMARY
The color used for input focus, selected date highlight, and hover border.

`style` _object_ **optional**
Additional component styles like setting the input width.

### CODE REVIEW

**Comment by lukeschunk** [comment]
This looks really good! if you don't mind I might want to look again tomorrow just since it's fairly large

**Comment by iheartrachie** [comment]
@lukeschunk Thanks for looking! Tomorrow is fine. 🍆

**Comment by lukeschunk** [comment]
Honestly this looks really good to me. One thing - and I'm not sure if this is with the date picker or with something in the demo app is you cant click to open the picker if you're in approximately the red area in the image below:

screen shot 2016-05-03 at 1 39 11 pm

**Comment by iheartrachie** [comment]
Oh dang, I'm glad you noticed that! I'll take a look and let you know when it's fixed.

**Comment by iheartrachie** [comment]
Fixed. Just had to move the onClick event handler up a div.
yoj5qwq7xx

**Comment by iheartrachie** [comment]
I somehow messed up with PR with duplicate commits and adding some from master that aren't even related. I'm going to redo this PR and we'll merge that when ready.

**Pull request closed without merging**
