### PR TITLE
Joe/tabs master

### PR DESCRIPTION
**Pull request by jtanner**
Everything in this branch was previously approved but I forgot to create a PR to merge this feature branch into master 😬 

Here's the main PR:
https://github.com/mxenabled/mx-react-components/pull/606

And here's the update for `theme`:
https://github.com/mxenabled/mx-react-components/pull/654

Let me know if you have any questions.

### CODE REVIEW

**Comment by paniclater** [comment]
:ship_it:

**Comment by lukeschunk** [comment]
:shipit:

**Comment by jtanner** [comment]
I checked this in IE and found a use of `overflow: scroll` that needed to be fixed.

**Comment by redperk** [comment]
:shipit:

**Pull request merged**
