### PR TITLE
MBD: updated docs with typo fixes

### PR DESCRIPTION
**Pull request by marabd**
this fixes typos found during QA review of the OS 6.0 release

### CODE REVIEW

**Comment by paniclater** [comment]
Typos look good, but tests failed?

**Comment by jmophoto** [comment]
Looks like the calendar test is set up assuming every month will show 5 weeks and checks the current month. Now that it is September, the calendar would show six weeks.

**Comment by jmophoto** [comment]
You could hard code a unix timestamp into the `selectedDate` prop in the test.

https://github.com/mxenabled/mx-react-components/blob/master/src/components/__tests__/Calendar-test.js#L25

Change
`selectedDate={moment().unix()}`

To
`selectedDate={'1533124800'}`

That would set it to always be August 1, 2018.

**Comment by jmophoto** [comment]
:shipit:

**Comment by paniclater** [comment]
:shipit:

**Pull request merged**
