### PR TITLE
Added CSS classes to allow styling

### LINKED ISSUE #31: Modal: Add css classes to allow styling through external stylesheets
This should be a fairly straight forward change and should not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/Modal`
- [ ] On line 23, add `className='mx-modal'` before the `style` prop declaration.
- [ ] On line 24, add `className='mx-modal-scrim'` before the `onClick` prop declaration.
- [ ] On line 25, add `className='mx-modal-content'` before the `style` prop declaration.
- [ ] On line 27, add `className='mx-modal-close'` on it's own line, before the `onClick` prop declaration.
- [ ] Open the demo and make sure your changes didn't break the Modal component.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #31` in the message
- [ ] Get merged and celebrate :tada:

### PR DESCRIPTION
**Pull request by Bravepeanut**
Fixes #31

### CODE REVIEW

**Comment by bsbeeks** [comment]
The changes to `Modal.js` look good! I'm not sure why there are changes to `.eslintrc`. If you remove those, then this should be ready to merge.

**Comment by Bravepeanut** [comment]
I removed the changes to .eslintrc

**Comment by bsbeeks** [comment]
Looks great! Congrats on your first open source contribution! :tada:

**Comment by Bravepeanut** [comment]
Thanks for helping out!

**Pull request merged**
