### PR TITLE
Add Accessibility to `Tab` Component

### PR DESCRIPTION
**Pull request by hokakede1**

### CODE REVIEW

**Comment by cerinman** [comment]
Huy, the code looks good.  Can you provide a screen shot of the the tab component in the docs showing the focus styling that you added?

**Comment by hokakede1** [comment]
screen shot 2018-08-10 at 3 56 01 pm
screen shot 2018-08-10 at 3 56 06 pm
screen shot 2018-08-10 at 3 56 10 pm

**Comment by cerinman** [comment]
Looks good but get with Derek and verify that he is ok with the focus styling and then I'll ship this. 👍

**Comment by hokakede1** [comment]
screen shot 2018-08-15 at 10 23 40 am
screen shot 2018-08-15 at 10 23 47 am
screen shot 2018-08-15 at 10 27 39 am

**Comment by cerinman** [comment]
:shipit:  👍 Queued for 5.2.25 release

**Pull request merged**
