### PR TITLE
Modal Height

### PR DESCRIPTION
**Pull request by iheartrachie**
We are seeing issues on internal projects where the height of the modal is exceeding the viewport and wasn't scrollable. I added some flex-box stuff the handle the modal height sizing.

## Before
9zhun7jwtn

## After
pthqeyoist

### CODE REVIEW

**Comment by jmophoto** [comment]
This looks good, but since it touches so many places, I would suggest testing locally before we move ahead.

**Comment by cerinman** [comment]
👍  from me as well but would be nice to have a confirmation around testing internally as Jason suggested to be safe.  We use the modal a lot.

**Comment by iheartrachie** [comment]
It's not work on internal apps and I suspect because of conflicts with flexbox. I'll keep poking around and will let ya'll know how this will be resolved.

**Comment by iheartrachie** [comment]
This doesn't fix the issue we're seeing internally but it doesn't break anything either. I'm completely stumped on what's going on internally because even the same modal content as demo (just images) isn't scrollable. There's obviously some conflicting CSS but I can't pinpoint it. If anyone else would like to take a stab at this, feel free. In the meantime, I'm going to close this PR.

**Pull request closed without merging**
